# Generated by Django 3.0.6 on 2020-05-18 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_auto_20200518_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodegaDashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bd_last_update', models.DateTimeField(blank=True, default=None, null=True, verbose_name='¿Last update')),
                ('bd_daily_sales', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('bd_weekly_sales', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('bd_monthly_sales', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('bd_last_day_sales', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('bd_last_week_sales', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('bd_last_month_sales', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('bd_daily_change_sales', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('bd_weekly_change_sales', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('bd_monthly_change_sales', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('bd_ID', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Bodega', verbose_name='Usuario')),
                ('bd_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Cliente', verbose_name='Usuario')),
            ],
        ),
    ]
