# Generated by Django 2.1.15 on 2020-04-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productos_aprobados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(choices=[('EM', 'Embutidos'), ('LA', 'Lácteos'), ('AB', 'Abarrotes'), ('LI', 'Limpieza'), ('LC', 'Licores'), ('VE', 'Vegetales'), ('OT', 'Otros')], default='OT', max_length=10)),
                ('product_title', models.CharField(max_length=100)),
                ('product_introduced', models.DateTimeField(auto_now=True)),
                ('product_description', models.TextField()),
                ('product_status', models.BooleanField()),
                ('product_photo_full', models.CharField(max_length=200)),
            ],
        ),
    ]
