# Generated by Django 3.0.6 on 2020-05-14 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodega',
            name='bd_email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='bodega',
            name='bd_phone',
            field=models.CharField(max_length=9, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='ci_cart_ID',
            field=models.IntegerField(default=0, verbose_name='Cart ID'),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('ord_ID', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID Order')),
                ('ord_taxes', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True)),
                ('ord_total_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True)),
                ('ord_date_updated', models.DateTimeField(auto_now=True)),
                ('ord_date_created', models.DateTimeField(auto_now_add=True)),
                ('ord_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ID Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oi_id_product', models.CharField(default='', max_length=100, verbose_name='ID Producto')),
                ('oi_product', models.CharField(default='', max_length=100, verbose_name='Producto')),
                ('oi_price', models.CharField(default='', max_length=100, verbose_name='Precio')),
                ('oi_prod_total', models.CharField(default='', max_length=100, verbose_name='Precio')),
                ('oi_quantity', models.CharField(default='', max_length=100, verbose_name='Cantidad')),
                ('oi_id_bodega', models.CharField(default='', max_length=100, verbose_name='ID Bodega')),
                ('oi_ruc_bodega', models.CharField(default='', max_length=100, verbose_name='RUC Bodega')),
                ('oi_bodega_name', models.CharField(default='', max_length=100, verbose_name='Nombre de Bodega')),
                ('oi_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Orders', verbose_name='ID Orden de Compra')),
            ],
        ),
    ]
