# Generated by Django 3.0.5 on 2020-04-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200425_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='crt_ID',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID Cart'),
        ),
    ]
