# Generated by Django 2.1.15 on 2020-04-17 17:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200417_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos_aprobados',
            name='product_introduced',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 17, 17, 13, 13, 865280, tzinfo=utc)),
        ),
    ]
