# Generated by Django 3.0.5 on 2020-04-27 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_auto_20200426_1853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productosaprobados',
            options={'verbose_name_plural': 'Productos aprobados'},
        ),
        migrations.RemoveField(
            model_name='cart',
            name='crt_quantity',
        ),
        migrations.AlterField(
            model_name='productosenbodega',
            name='peb_ID',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID Productos en bodegas'),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci_cart_ID', models.IntegerField(default=0, verbose_name='ID Cart ID')),
                ('ci_quantity', models.IntegerField(default=1)),
                ('ci_date_updated', models.DateTimeField(auto_now=True)),
                ('ci_date_created', models.DateTimeField(auto_now_add=True)),
                ('ci_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ProductosEnBodega', verbose_name='Producto')),
                ('ci_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ID Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='crt_item',
            field=models.ManyToManyField(blank=True, to='main.CartItem', verbose_name='Item'),
        ),
    ]
