# Generated by Django 3.0.5 on 2020-05-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200427_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cl_bodega_ID',
            field=models.CharField(blank=True, default='', max_length=36, null=True, verbose_name='ID Bodega'),
        ),
    ]
