# Generated by Django 3.0.5 on 2020-04-18 17:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200418_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos_aprobados',
            name='product_introduced',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 18, 17, 49, 13, 747106, tzinfo=utc)),
        ),
    ]
