# Generated by Django 3.0.5 on 2020-04-19 00:24

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200418_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoOfertado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_regular_price', models.FloatField()),
                ('po_discount_price', models.FloatField()),
                ('po_discount_rate', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Producto ofertado',
            },
        ),
        migrations.CreateModel(
            name='ProductosAprobados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pa_category', models.CharField(choices=[('EM', 'Embutidos'), ('LA', 'Lácteos'), ('AB', 'Abarrotes'), ('LI', 'Limpieza'), ('LC', 'Licores'), ('VE', 'Vegetales'), ('OT', 'Otros')], default='OT', max_length=10)),
                ('pa_title', models.CharField(max_length=100)),
                ('pa_introduced', models.DateTimeField(default=datetime.datetime(2020, 4, 19, 0, 24, 46, 163699, tzinfo=utc))),
                ('pa_description', models.TextField(default='noDescription')),
                ('pa_status', models.BooleanField()),
                ('pa_photo_full', models.CharField(default='noPhoto', max_length=200)),
                ('pa_photo_mid', models.CharField(default='noPhoto', max_length=200)),
                ('pa_photo_small', models.CharField(default='noPhoto', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Productos aprobados',
            },
        ),
        migrations.CreateModel(
            name='ProductosListados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pl_productos', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.ProductosAprobados', verbose_name='Productos listados')),
            ],
            options={
                'verbose_name_plural': 'Lista de productos',
            },
        ),
        migrations.DeleteModel(
            name='productos_aprobados',
        ),
        migrations.AddField(
            model_name='productoofertado',
            name='po_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ProductosAprobados'),
        ),
    ]
