# Generated by Django 3.0.5 on 2020-04-19 00:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200419_0224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productosaprobados',
            name='pa_title',
        ),
        migrations.AddField(
            model_name='productosaprobados',
            name='pa_brand',
            field=models.CharField(default='marca', max_length=100, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='productosaprobados',
            name='pa_product',
            field=models.CharField(default='producto', max_length=100, verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='productosaprobados',
            name='pa_category',
            field=models.CharField(choices=[('EM', 'Embutidos'), ('LA', 'Lácteos'), ('AB', 'Abarrotes'), ('LI', 'Limpieza'), ('LC', 'Licores'), ('VE', 'Vegetales'), ('OT', 'Otros')], default='OT', max_length=10, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='productosaprobados',
            name='pa_description',
            field=models.TextField(default='sinDsescripción', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='productosaprobados',
            name='pa_introduced',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 0, 46, 27, 101576, tzinfo=utc), verbose_name='Fecha de introducción'),
        ),
        migrations.AlterField(
            model_name='productosaprobados',
            name='pa_photo_full',
            field=models.CharField(default='noPhoto', max_length=200, verbose_name='Foto grande'),
        ),
        migrations.AlterField(
            model_name='productosaprobados',
            name='pa_photo_mid',
            field=models.CharField(default='noPhoto', max_length=200, verbose_name='Foto mediana'),
        ),
        migrations.AlterField(
            model_name='productosaprobados',
            name='pa_photo_small',
            field=models.CharField(default='noPhoto', max_length=200, verbose_name='Foto pequeña'),
        ),
        migrations.AlterField(
            model_name='productosaprobados',
            name='pa_status',
            field=models.BooleanField(verbose_name='Activo'),
        ),
    ]
