# Generated by Django 3.0.5 on 2020-04-19 01:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20200419_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosaprobados',
            name='pa_reg_sanitario',
            field=models.CharField(default='', max_length=100, verbose_name='Registro sanitario'),
        ),
        migrations.AlterField(
            model_name='productosaprobados',
            name='pa_brand',
            field=models.CharField(default='', max_length=100, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='productosaprobados',
            name='pa_introduced',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 1, 44, 54, 193724, tzinfo=utc), verbose_name='Fecha de introducción'),
        ),
        migrations.AlterField(
            model_name='productosaprobados',
            name='pa_product',
            field=models.CharField(default='', max_length=100, verbose_name='Producto'),
        ),
    ]
