# Generated by Django 3.0.5 on 2020-04-19 01:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20200419_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productosaprobados',
            name='pa_introduced',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 1, 47, 38, 396942, tzinfo=utc), verbose_name='Fecha de introducción'),
        ),
        migrations.AlterField(
            model_name='productosaprobados',
            name='pa_product',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Producto'),
        ),
    ]
