# Generated by Django 3.0.5 on 2020-04-19 01:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20200419_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productosaprobados',
            name='pa_introduced',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 1, 49, 4, 491181, tzinfo=utc), verbose_name='Fecha de introducción'),
        ),
        migrations.AlterField(
            model_name='productosaprobados',
            name='pa_product',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Producto'),
        ),
    ]
