# Generated by Django 3.0.5 on 2020-04-19 01:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20200419_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productosaprobados',
            name='pa_introduced',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 1, 52, 19, 894370, tzinfo=utc), verbose_name='Fecha de introducción'),
        ),
        migrations.AlterField(
            model_name='productosaprobados',
            name='pa_photo_full',
            field=models.CharField(blank=True, default='noPhoto', max_length=200, verbose_name='Foto grande'),
        ),
        migrations.AlterField(
            model_name='productosaprobados',
            name='pa_photo_mid',
            field=models.CharField(blank=True, default='noPhoto', max_length=200, verbose_name='Foto mediana'),
        ),
        migrations.AlterField(
            model_name='productosaprobados',
            name='pa_photo_small',
            field=models.CharField(blank=True, default='noPhoto', max_length=200, verbose_name='Foto pequeña'),
        ),
        migrations.AlterField(
            model_name='productosaprobados',
            name='pa_product',
            field=models.CharField(default='', max_length=100, verbose_name='Producto'),
        ),
    ]
