# Generated by Django 3.0.5 on 2020-04-19 08:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20200419_0352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoofertado',
            name='po_discount_rate',
        ),
        migrations.AddField(
            model_name='productoofertado',
            name='pa_discount_status',
            field=models.BooleanField(default=False, verbose_name='Vender con el descuento'),
        ),
        migrations.AlterField(
            model_name='productoofertado',
            name='po_discount_price',
            field=models.FloatField(blank=True, verbose_name="'%' de desucento"),
        ),
        migrations.AlterField(
            model_name='productoofertado',
            name='po_regular_price',
            field=models.FloatField(verbose_name='Precio regular'),
        ),
        migrations.AlterField(
            model_name='productosaprobados',
            name='pa_introduced',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 8, 19, 4, 692135, tzinfo=utc), verbose_name='Fecha de introducción'),
        ),
    ]
