# Generated by Django 3.0.5 on 2020-04-19 08:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20200419_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productosaprobados',
            name='pa_introduced',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 8, 19, 41, 330216, tzinfo=utc), verbose_name='Fecha de introducción'),
        ),
    ]
