# Generated by Django 3.0.5 on 2020-04-19 08:54

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20200419_1049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productoofertado',
            options={'verbose_name_plural': 'Producto en bodega'},
        ),
        migrations.AlterModelOptions(
            name='productoslistados',
            options={'verbose_name_plural': 'Todos los productos listados en bodega'},
        ),
        migrations.AlterField(
            model_name='productosaprobados',
            name='pa_introduced',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 8, 54, 51, 125383, tzinfo=utc), verbose_name='Fecha de introducción'),
        ),
        migrations.AlterField(
            model_name='productoslistados',
            name='pl_productos',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.ProductoOfertado', verbose_name='Lista de productos'),
        ),
    ]
