# Generated by Django 3.0.5 on 2020-04-19 08:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20200419_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productosaprobados',
            options={'verbose_name_plural': 'Productos aceptados'},
        ),
        migrations.AlterField(
            model_name='productosaprobados',
            name='pa_introduced',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 8, 55, 39, 943867, tzinfo=utc), verbose_name='Fecha de introducción'),
        ),
    ]
