# Generated by Django 3.0.5 on 2020-04-19 09:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20200419_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoofertado',
            name='po_discount_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Precio con descuento'),
        ),
        migrations.AlterField(
            model_name='productosaprobados',
            name='pa_introduced',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 9, 5, 35, 3548, tzinfo=utc), verbose_name='Fecha de introducción'),
        ),
    ]
