# Generated by Django 3.0.5 on 2020-04-19 10:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20200419_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoofertado',
            name='id',
        ),
        migrations.AddField(
            model_name='productoofertado',
            name='po_ID',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=10, primary_key=True, serialize=False, verbose_name='Código de listado'),
        ),
        migrations.AlterField(
            model_name='productosaprobados',
            name='pa_introduced',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 10, 49, 44, 432947, tzinfo=utc), verbose_name='Fecha de introducción'),
        ),
        migrations.DeleteModel(
            name='ProductosListados',
        ),
    ]
