# Generated by Django 3.0.5 on 2020-04-19 10:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20200419_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoofertado',
            name='po_ID',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=32, primary_key=True, serialize=False, verbose_name='Código de listado'),
        ),
        migrations.AlterField(
            model_name='productosaprobados',
            name='pa_introduced',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 10, 50, 6, 857331, tzinfo=utc), verbose_name='Fecha de introducción'),
        ),
    ]
