# Generated by Django 3.0.5 on 2020-04-19 10:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20200419_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoofertado',
            name='po_ID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Código de listado'),
        ),
        migrations.AlterField(
            model_name='productosaprobados',
            name='pa_introduced',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 10, 53, 10, 808501, tzinfo=utc), verbose_name='Fecha de introducción'),
        ),
    ]
