# Generated by Django 3.0.5 on 2020-04-19 12:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20200419_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaDeProductos',
            fields=[
                ('ldp_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Código de listado')),
                ('ldp_regular_price', models.FloatField(verbose_name='Precio regular')),
                ('ldp_discount_price', models.FloatField(blank=True, null=True, verbose_name='Precio con descuento')),
                ('ldp_discount_status', models.BooleanField(default=False, verbose_name='Vender con el descuento')),
            ],
            options={
                'verbose_name_plural': 'Producto en bodega',
            },
        ),
        migrations.RemoveField(
            model_name='productosaprobados',
            name='id',
        ),
        migrations.AddField(
            model_name='productosaprobados',
            name='pa_ID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Código de listado'),
        ),
        migrations.AlterField(
            model_name='productosaprobados',
            name='pa_introduced',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 12, 27, 57, 900579, tzinfo=utc), verbose_name='Fecha de introducción'),
        ),
        migrations.DeleteModel(
            name='ProductoOfertado',
        ),
        migrations.AddField(
            model_name='listadeproductos',
            name='ldp_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ProductosAprobados'),
        ),
    ]
