# Generated by Django 3.0.5 on 2020-04-19 12:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20200419_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productosaprobados',
            name='pa_introduced',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 12, 28, 5, 400493, tzinfo=utc), verbose_name='Fecha de introducción'),
        ),
    ]
