# Generated by Django 3.0.5 on 2020-04-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20200419_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productosaprobados',
            name='pa_introduced',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de introducción'),
        ),
    ]
