# Generated by Django 3.0.5 on 2020-04-19 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20200419_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listadeproductos',
            options={'verbose_name_plural': 'Lista De Productos'},
        ),
        migrations.AddField(
            model_name='listadeproductos',
            name='ldp_status',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
        migrations.AlterField(
            model_name='listadeproductos',
            name='ldp_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ProductosAprobados', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='productosaprobados',
            name='pa_status',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
