# Generated by Django 3.0.5 on 2020-04-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20200419_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='listadeproductos',
            name='ldp_discount_rate',
            field=models.FloatField(default=0, editable=False, verbose_name="'%' de descuento"),
        ),
    ]
