# Generated by Django 3.0.5 on 2020-04-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_listadeproductos_ldp_discount_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listadeproductos',
            name='ldp_discount_rate',
            field=models.FloatField(default=0, verbose_name="'%' de descuento"),
        ),
    ]
