# Generated by Django 3.0.5 on 2020-04-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_auto_20200419_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productosaprobados',
            name='pa_category',
            field=models.CharField(choices=[('Embutidos', 'Embutidos'), ('Lacteos', 'Lácteos'), ('Abarrotes', 'Abarrotes'), ('Limpieza', 'Limpieza'), ('Licores', 'Licores'), ('Vegetales', 'Vegetales'), ('Otros', 'Otros')], default='Otros', max_length=10, verbose_name='Categoría'),
        ),
    ]
