# Generated by Django 3.0.5 on 2020-04-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_auto_20200419_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productosaprobados',
            name='pa_category',
            field=models.CharField(choices=[('EM', 'Embutidos'), ('LA', 'Lácteos'), ('AB', 'Abarrotes'), ('LI', 'Limpieza'), ('LC', 'Licores'), ('VE', 'Vegetales'), ('OT', 'Otros')], default='OT', max_length=10, verbose_name='Categoría'),
        ),
    ]
