# Generated by Django 3.0.5 on 2020-04-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_auto_20200419_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productosaprobados',
            name='pa_category',
            field=models.CharField(choices=[('embutidos', 'Embutidos'), ('lacteos', 'Lácteos'), ('abarrotes', 'Abarrotes'), ('limpieza', 'Limpieza'), ('licores', 'Licores'), ('vegetales', 'Vegetales'), ('otros', 'Otros')], default='otros', max_length=10, verbose_name='Categoría'),
        ),
    ]
