# Generated by Django 3.0.5 on 2020-04-20 13:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_auto_20200419_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('bkt_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Código de cesto')),
                ('bkt_quantity', models.IntegerField(default=1)),
                ('bkt_product', models.ManyToManyField(to='main.ListaDeProductos')),
            ],
        ),
    ]
