# Generated by Django 3.0.5 on 2020-04-20 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_auto_20200420_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listadeproductos',
            old_name='ldp_Cod',
            new_name='ldp_cod',
        ),
    ]
