# Generated by Django 3.0.5 on 2020-04-20 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0048_auto_20200420_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listadeproductos',
            name='ldp_cod',
            field=models.CharField(default='000000', max_length=6, unique=True, verbose_name='Código de listado'),
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bd_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dirreción')),
                ('bd_geo_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ubicación')),
                ('bd_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Bodega')),
            ],
        ),
    ]
