# Generated by Django 3.0.5 on 2020-04-20 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0049_auto_20200420_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodega',
            name='bd_address',
        ),
        migrations.RemoveField(
            model_name='bodega',
            name='bd_geo_address',
        ),
        migrations.RemoveField(
            model_name='bodega',
            name='id',
        ),
        migrations.RemoveField(
            model_name='listadeproductos',
            name='ldp_ID',
        ),
        migrations.AddField(
            model_name='bodega',
            name='bd_ID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID Bodega'),
        ),
        migrations.AddField(
            model_name='bodega',
            name='bd_is_active',
            field=models.BooleanField(default=True, verbose_name='¿Está activo?'),
        ),
        migrations.AddField(
            model_name='bodega',
            name='bd_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bodega'),
        ),
        migrations.AddField(
            model_name='bodega',
            name='bd_raz_soc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bodega'),
        ),
        migrations.AddField(
            model_name='bodega',
            name='bd_ruc',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Bodega'),
        ),
        migrations.AddField(
            model_name='listadeproductos',
            name='lpd_ID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID Listado'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='bkt_ID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID Cesto'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='bkt_product',
            field=models.ManyToManyField(null=True, to='main.ListaDeProductos', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='listadeproductos',
            name='ldp_cod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Bodega', verbose_name='Código de listado'),
        ),
        migrations.AlterField(
            model_name='productosaprobados',
            name='pa_ID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID Producto'),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cl_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID Cliente')),
                ('cl_first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre')),
                ('cl_last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido')),
                ('cl_phone', models.CharField(max_length=9, null=True, verbose_name='Celular')),
                ('cl_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dirreción')),
                ('cl_geolocation', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ubicación')),
                ('cl_date_reg', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('cl_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
        ),
        migrations.AddField(
            model_name='basket',
            name='bkt_cod',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Cliente', verbose_name='ID Cliente'),
        ),
        migrations.AlterField(
            model_name='bodega',
            name='bd_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Cliente', verbose_name='Bodega'),
        ),
    ]
