# Generated by Django 3.0.5 on 2020-04-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_auto_20200420_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='bkt_product',
            field=models.ManyToManyField(to='main.ListaDeProductos', verbose_name='Producto'),
        ),
    ]
